// Package ffmpeg provides video encoding utilities backed by ffmpeg binary.
package ffmpeg

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const defaultEncodeTimeout = 2 * time.Minute

type FFmpegService struct {
	binaryPath string
}

func New(binaryPath string) (*FFmpegService, error) {
	if strings.TrimSpace(binaryPath) == "" {
		return nil, errors.New("ffmpeg binary path is empty")
	}

	return &FFmpegService{binaryPath: binaryPath}, nil
}

func (s *FFmpegService) Transcode(ctx context.Context, inputPath string) (string, error) {
	if ctx == nil {
		return "", errors.New("context is nil")
	}
	if strings.TrimSpace(inputPath) == "" {
		return "", errors.New("input path is empty")
	}

	outputPath := encodedOutputPath(inputPath)

	runCtx, cancel := context.WithTimeout(ctx, defaultEncodeTimeout)
	defer cancel()

	cmd := exec.CommandContext(
		runCtx,
		s.binaryPath,
		"-y",
		"-i", inputPath,
		"-map", "0:v:0",
		"-map", "0:a:0?",
		"-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2,setsar=1,format=yuv420p",
		"-metadata:s:v:0", "rotate=0",
		"-c:v", "libx264",
		"-preset", "superfast",
		"-crf", "21",
		"-maxrate", "6M",
		"-bufsize", "12M",
		"-profile:v", "high",
		"-level", "4.1",
		"-c:a", "aac",
		"-profile:a", "aac_low",
		"-b:a", "128k",
		"-ar", "48000",
		"-ac", "2",
		"-movflags", "+faststart",
		outputPath,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("run ffmpeg: %w (stderr: %s)", err, strings.TrimSpace(stderr.String()))
	}

	return outputPath, nil
}

// CreateThumnail creates a thumbnail for the given video file and returns the path to the thumbnail image.
// The thumbnail is generated by extracting a frame at one second.
func (s *FFmpegService) CreateThumnail(ctx context.Context, path string) (string, error) {
	if ctx == nil {
		return "", errors.New("context is nil")
	}
	if strings.TrimSpace(path) == "" {
		return "", errors.New("input path is empty")
	}

	outputPath := thumbnailOutputPath(path)

	runCtx, cancel := context.WithTimeout(ctx, defaultEncodeTimeout)
	defer cancel()

	cmd := exec.CommandContext(
		runCtx,
		s.binaryPath,
		"-y",
		"-ss", "1",
		"-i", path,
		"-frames:v", "1",
		"-q:v", "2",
		outputPath,
	)

	var stderr bytes.Buffer
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("create thumbnail: %w (stderr: %s)", err, strings.TrimSpace(stderr.String()))
	}

	return outputPath, nil
}

func encodedOutputPath(inputPath string) string {
	ext := filepath.Ext(inputPath)
	if ext == "" {
		return inputPath + ".encoded.mp4"
	}

	return strings.TrimSuffix(inputPath, ext) + ".encoded.mp4"
}

func thumbnailOutputPath(inputPath string) string {
	ext := filepath.Ext(inputPath)
	if ext == "" {
		return inputPath + ".thumb.jpg"
	}

	return strings.TrimSuffix(inputPath, ext) + ".thumb.jpg"
}
